[2024-04-23T15:20:15.294+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T15:20:15.308+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-23T15:20:15.312+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-23T15:20:15.312+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-23T15:20:15.318+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-04-22 00:00:00+00:00
[2024-04-23T15:20:15.322+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2024-04-22T00:00:00+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpi18ipz27']
[2024-04-23T15:20:15.323+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1501) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-23T15:20:15.323+0000] {standard_task_runner.py:91} INFO - Job 413: Subtask create_postgres_table
[2024-04-23T15:20:15.323+0000] {standard_task_runner.py:63} INFO - Started process 1503 to run task
[2024-04-23T15:20:15.343+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-04-22T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-23T15:20:15.380+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-22T00:00:00+00:00'
[2024-04-23T15:20:15.381+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T15:20:15.388+0000] {sql.py:276} INFO - Executing: 
            create table if not exists dag_runs (
            dt date,
            dag_id character varying,
            primary key (dt, dag_id)
            )
        
[2024-04-23T15:20:15.392+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-23T15:20:15.397+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-23T15:20:23.402+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T15:20:23.408+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2024-04-23T15:20:23.432+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20240422T000000, start_date=20240423T152015, end_date=20240423T152023
[2024-04-23T15:20:23.445+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 413 for task create_postgres_table (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 1503)
[2024-04-23T15:20:23.468+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-23T15:20:23.478+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T15:20:23.479+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-23T15:23:36.646+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T15:23:36.659+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-23T15:23:36.663+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-23T15:23:36.663+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-23T15:23:36.669+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-04-22 00:00:00+00:00
[2024-04-23T15:23:36.673+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2024-04-22T00:00:00+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpa2gksjvi']
[2024-04-23T15:23:36.675+0000] {standard_task_runner.py:91} INFO - Job 415: Subtask create_postgres_table
[2024-04-23T15:23:36.675+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1751) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-23T15:23:36.676+0000] {standard_task_runner.py:63} INFO - Started process 1753 to run task
[2024-04-23T15:23:36.704+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-04-22T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-23T15:23:36.741+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-22T00:00:00+00:00'
[2024-04-23T15:23:36.742+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T15:23:36.750+0000] {sql.py:276} INFO - Executing: 
            create table if not exists dag_runs (
            dt date,
            dag_id character varying,
            primary key (dt, dag_id)
            )
        
[2024-04-23T15:23:36.754+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-23T15:23:36.760+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-23T15:23:36.768+0000] {sql.py:457} INFO - Running statement: 
            create table if not exists dag_runs (
            dt date,
            dag_id character varying,
            primary key (dt, dag_id)
            )
        , parameters: None
[2024-04-23T15:23:36.777+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:407 AirflowProviderDeprecationWarning: Call to deprecated method _make_common_data_structure. (The `_make_serializable` method is deprecated and support will be removed in a future version of the common.sql provider. Please update the DbApiHook's provider to a version based on common.sql >= 1.9.1.)
[2024-04-23T15:23:36.778+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T15:23:36.783+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20240422T000000, start_date=20240423T152336, end_date=20240423T152336
[2024-04-23T15:23:36.816+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-23T15:23:36.823+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T15:23:36.824+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
